apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    persistentvolumeclaims: "30"
    services: "20" 
    pods: "30"

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-scoped
spec:
  hard:
    requests.memory: 2Gi
    requests.cpu: 1000m
    limits.memory: 2Gi
    limits.cpu: 1000m
  scopes:
  - NotTerminating