kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: iotpaas-message-producer
    name: iotpaas-message-producer
  name: iotpaas-message-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iotpaas-message-producer
  strategy:
    #activeDeadlineSeconds: 21600
    #resources: {}
    #rollingParams:
    #  intervalSeconds: 1
    #  maxSurge: 25%
    #  maxUnavailable: 25%
    #  timeoutSeconds: 600
    #  updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iotpaas-message-producer
        name: iotpaas-message-producer
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: trace
        - name: VERSION
          value: 1.0.1
        - name: SERVER_PORT
          value: "9000"
        - name: TOPIC
          value: iotdata
        image: quay.io/luigizuccarelli/iotpaas-message-producer:1.16.6
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/v2/sys/info/isalive
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 55
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: iotpaas-message-producer
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /api/v2/sys/info/isalive
            port: 9000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      #imagePullSecrets:
      #- name: quay.registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
   #test: false
   #triggers:
   #- type: ConfigChange
