kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: iotpaas-message-consumer
    name: iotpaas-message-consumer
  name: iotpaas-message-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iotpaas-message-consumer
  strategy:
    #resources: {}
    #rollingParams:
    #  intervalSeconds: 1
    #  maxSurge: 25%
    #  maxUnavailable: 25%
    #  timeoutSeconds: 600
    #  updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iotpaas-message-consumer
        name: iotpaas-message-consumer
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: info
        - name: VERSION
          value: 1.0.4
        - name: NAME
          value: iotpaas-message-consumer
        - name: REDIS_USER
          value: Administrator
        - name: REDIS_HOST
          value: redis-cluster.redis-cluster.svc.cluster.local:6379
        - name: SERVER_PORT
          value: "9000"
        - name: KAFKA_BROKERS
          value: "kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092"
        - name: REDIS_PASSWORD
          value: "test"
          #- name: REDIS_PASSWORD
          #valueFrom:
          #  secretKeyRef:
          #    key: database-password
          #    name: iotpaas-secret
          #- name: COUCHBASE_ADMIN_PASSWORD
          #valueFrom:
          #  secretKeyRef:
          #    key: database-password
          #    name: iotpaas-secret
          #- name: COUCHBASE_BUCKET
          #value: iotdata
        - name: TOPIC
          value: iotdata
        image: quay.io/luigizuccarelli/iotpaas-message-consumer-redis:1.16.6
        imagePullPolicy: Always
        name: iotpaas-message-consumer
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      #imagePullSecrets:
      #- name: quay.registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  # test: false
  # triggers:
  #- type: ConfigChange
