kind: Service
apiVersion: v1
metadata:
  labels:
    app: iotpaas-message-consumer
    name: iotpaas-message-consumer
  name: iotpaas-message-consumer
spec:
  ports:
  - name: consumer-port
    port: 7001
    protocol: TCP
    targetPort: 7001
  selector:
    name: iotpaas-message-consumer
  sessionAffinity: None
  type: ClusterIP
