apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
spec:
  entityOperator:
    metrics: {}
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 100Mi
    topicOperator: {}
    userOperator: {}
  kafka:
    tlsSidecar:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
    config:
      log.message.format.version: '2.4'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    metrics:
      lowercaseOutputName: true
    resources:
      limits:
        cpu: 1000m
        memory: 1200Mi
      requests:
        cpu: 200m
        memory: 200Mi
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 15
      timeoutSeconds: 15
    livenessProbe:
      exec:
        command:
          - /opt/kafka/kafka_liveness.sh
      failureThreshold: 3
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    version: 2.4.0
    storage:
      type: jbod
      volumes:
        - class: gp2
          deleteClaim: false
          id: 0
          size: 30Gi
          type: persistent-claim
    replicas: 3
    jvmOptions:
      '-Xms': 1024m
      '-Xmx': 1024m
    listeners:
      plain: {}
      tls: {}
  zookeeper:
    metrics:
      lowercaseOutputName: true
    replicas: 3
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 100Mi
    storage:
      deleteClaim: false
      size: 5Gi
      type: persistent-claim
    tlsSidecar:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi