kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trackmate-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: trackmate-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin