apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: metadata
spec:
  name: metadata
  memoryQuota: 256Mi
  replicas: 1
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: lww
  enableFlush: true
  enableIndexReplica: true
  compressionMode: passive
